source "https://rubygems.org"

gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem 'pry'

#testing
gem 'rspec'
gem 'guard'
gem 'guard-rspec'
gem 'simplecov'

#converter api
gem 'money'
gem 'eu_central_bank'